version: '3.8'
services:
  back:
    build: ./back
    container_name: back_container
    depends_on:
      - database
    networks:
      - app-network
    environment:
      - WAIT_HOSTS=database:5432
      - PORT=5000
      - SALT=10
      - PRIVATE_KEY=secretKey
      - EXPIRES_IN=365d
      - DATABASE_NAME=tictactoe
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=strongpassword
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
    ports:
      - '5000:5000'

  database:
    image: postgres:16
    container_name: database_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: tictactoe
    ports:
      - '5432:5432'
    volumes: 
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  front:
    build:
      context: ./front
      args:
        - REACT_APP_API_ENDPOINT=http://localhost:5000
    container_name: front_container
    ports:
      - '3000:3000'
    tty: true

networks:
  app-network:
    driver: bridge
    
volumes: 
  db-data: